library(lubridate)
df <- read.csv('household_power_consumption.txt', header = TRUE, sep = ';')
df <- df[df$Date == '1/2/2007' | df$Date == '2/2/2007' | (df$Date == '3/2/2007' & df$Time == '00:00:00'),]
td <- as.character(df$Date)
hs <- as.character(df$Time)
Time <- paste(td, hs, sep = ' ')
Time <- strptime(Time, '%d/%m/%Y %H:%M:%S')
Date <- as.Date(df$Date, '%d/%m/%Y')
GAP<- as.numeric(as.character(df$Global_active_power))
quartz()
plot(Time, GAP, xaxt = "n", type = "l", xlab = '', ylab = 'Global Active Power(kilowatts)')
axis.POSIXct(side=1, at=cut(Time, "days"), format="%a") 
dev.copy(png,'plot2.png')
dev.off()
